language: node_js
node_js:
  - node
deploy:
  provider: heroku
  app: rocky-earth-98239
  api_key:
    secure: IjMXIrrjg6AtJDubKCk1HsYUycICHVTzwICojiM0HerX07O70OG/MHB6Q0ES18jaeilil3cTV/tNQ/eTFR644Ity++klCSVSnMn38I7MLzQg9JWsy/IKvXZx9Bila61L7mpAmdAzvp6j8QgTiwUJ+RKF5NvXQBwDuf4iDS8wqKbAioJRcAbDU9No7bcQDEL78eTewhrfFHntc4RdYKV9ZNpMTPIzx8mJaFTWDpdoCgCatcYoqX/V887qaJjjvGno394Rsee8AqHrqQar0WhbzCW5gNiikwmB7vOdS+iOWYvDXSR3aklLrmhdkfTGLBszjbvRRFBdP/n0CQnbhaMcpi9nRT3EMzPm+8FXwoNo2+Cu1Yi+pdfbv4XeQyrQhsVfOzcwvokCm/h/tmII/Zqhz5Gp/nv/j+m7v4UIv7dHfLV4yWNsjMvnmDjWQJahr8zBQndnpCBz/Z1ImwX7x23mnMNEZ++REFD6QTl81vyWr/WOn0VlJZWJi4Tw1KCnC2UzKRbPO/t3bYU1ykeiOa6xgcW4p3JlCmpsE28BJnUM2vId99rT37k/fD3xsf0krNfv3/aT9tBhX2//oQ+eof0FbqsRsXXu4ZBUlBdlXbIDKTdEi0u7iu09nst/rBqpLtnOH0fnOn6KDL7FDex38XPd+TTwRW/VaOI/nRoffoGcfO8=
